In [ ]:
#Numpy Crash Course

In [2]:
import numpy as np

In [ ]:
import sys 
sys.version

In [9]:
np.__version__

'1.26.4'

In [5]:
#Creating Arrays  

In [6]:
my_list =  [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [7]:
type(my_list)

list

In [8]:
arr = np.array(my_list)

In [10]:
arr

array([0, 1, 2, 3, 4, 5])

In [11]:
type(arr)

numpy.ndarray

In [12]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
np.arange(3.0)

array([0., 1., 2.])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [16]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(-20,20)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19])

In [19]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [20]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [22]:
np.arange(30,20)


array([], dtype=int32)

In [25]:
ar = np.arange(-30,20)
arr

array([0, 1, 2, 3, 4, 5])

In [26]:
np.arange(10,10)

array([], dtype=int32)

In [27]:
np.arange()

TypeError: arange() requires stop to be specified.

In [28]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [29]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [30]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [31]:
np.zeros(3) # parameter tunning

array([0., 0., 0.])

In [32]:
np.zeros(5,dtype=int) # hyperparameter tunning

array([0, 0, 0, 0, 0])

In [33]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [34]:
zero=np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [35]:
zero=np.zeros([2,2])
print(zero)
print('####')
print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [36]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [38]:
np.zeros((5,10)) # bydeful large -- will give row 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [41]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunning

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [42]:
print(np.zeros(n,dtype=int)) # hyperparameter tunning

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [43]:
n

(6, 7)

In [44]:
n1

(6, 8)

In [45]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [46]:
np.ones(3)

array([1., 1., 1.])

In [47]:
np.ones(4, dtype = int )

array([1, 1, 1, 1])

In [48]:
np.ones(4)

array([1., 1., 1., 1.])

In [49]:
n

(6, 7)

In [50]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [51]:
np.ones((5,4),dtype=int) # by default 5 - rows & 4

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [52]:
np.ones(2)

array([1., 1.])

In [53]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
np.ones((6,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [55]:
np.three((2,4))

AttributeError: module 'numpy' has no attribute 'three'

In [56]:
range(5)

range(0, 5)

In [58]:
r=range(5)
r

range(0, 5)

In [61]:
for i in r:
    print(i)

0
1
2
3
4


In [62]:
list(range(5))

[0, 1, 2, 3, 4]

In [63]:
range(1,10)

range(1, 10)

In [64]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [65]:
list(range(1,10,3))

[1, 4, 7]

In [67]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [68]:
rand(3,2)

NameError: name 'rand' is not defined

In [70]:
rand(3,2)
ramndom.rand(3,2)

NameError: name 'rand' is not defined

In [71]:
np.random.rand(5)

array([0.62700748, 0.0781405 , 0.84432876, 0.07778817, 0.5723929 ])

In [72]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [73]:
np.random.rand(2,4)

array([[0.31506571, 0.46583461, 0.62898079, 0.96458266],
       [0.9895049 , 0.41355013, 0.77952923, 0.50233159]])

In [74]:
np.random.randint(2,4)

2

In [75]:
np.random.randint(0,1)

0

In [77]:
np.random.randint(2,20)

16

In [78]:
np.random.randint(10,20,5)

array([19, 12, 15, 18, 11])

In [79]:
np.random.randint(1,6,4)

array([5, 3, 1, 5])

In [80]:
np.random.rand(3)

array([0.10976799, 0.18475407, 0.19137044])

In [81]:
np.random.randint(30,20,10)

ValueError: low >= high

In [82]:
np.random.randint(-30,20,10)

array([-29, -27, -26,  14,   4,   8,  12,   3, -21, -25])

In [83]:
np.random.randint(20,30,10)

array([24, 26, 26, 26, 26, 24, 28, 29, 24, 24])

In [84]:
np.random.randint(20,30,10) 

array([21, 22, 24, 23, 24, 23, 28, 27, 21, 22])

In [85]:
np.random.randint(5,9) 

7

In [86]:
np.random.randint(10,21,3)

array([13, 10, 14])

In [87]:
np.random.randint(10,40,(10,10)) 

array([[13, 28, 36, 28, 35, 26, 32, 17, 19, 17],
       [12, 27, 33, 20, 27, 19, 33, 23, 15, 10],
       [10, 15, 15, 22, 10, 20, 12, 25, 36, 17],
       [17, 13, 17, 26, 20, 37, 24, 30, 20, 19],
       [10, 27, 37, 22, 26, 20, 15, 36, 28, 18],
       [13, 10, 15, 15, 39, 12, 16, 19, 36, 19],
       [31, 27, 35, 27, 23, 32, 25, 31, 26, 11],
       [10, 28, 12, 11, 39, 27, 36, 14, 14, 32],
       [28, 25, 21, 28, 37, 34, 31, 37, 11, 24],
       [21, 39, 20, 19, 25, 10, 20, 38, 22, 11]])

In [88]:
np.random.randint(1,100,(12,12)) 

array([[31, 35, 47, 96, 47,  2, 58, 47, 97, 62,  4, 65],
       [ 3,  4, 96, 61, 94, 19, 70, 31,  7, 27,  5, 29],
       [90, 11, 59, 64,  3, 17, 60, 43, 37, 83, 52, 14],
       [ 2, 65, 64, 71, 99, 18, 87, 28, 21, 87, 20, 54],
       [89, 45,  8, 39, 48, 91, 51, 20, 86, 27,  8, 51],
       [47, 96, 27, 52, 47,  9, 16, 77, 25, 17, 87, 39],
       [16, 14, 42,  1, 64, 81, 39, 36, 80, 89, 30, 97],
       [ 5, 91, 92, 49, 17, 75, 56, 75, 30, 12, 88, 66],
       [94, 65, 28, 86, 90, 93, 71, 81, 86, 69, 52, 79],
       [99, 46, 50, 96, 31, 29, 31, 67, 29,  7, 12, 55],
       [38, 82,  6, 57, 43, 16, 89, 96, 29, 67, 75, 46],
       [70, 96, 93, 82, 78, 34, 58, 54, 47, 43, 30, 24]])

In [89]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [90]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [91]:
b = np.random.randint(10,20,(5,4))
b

array([[18, 12, 12, 10],
       [16, 10, 12, 11],
       [19, 17, 15, 16],
       [12, 16, 15, 19],
       [15, 15, 17, 13]])

In [92]:
type(b)

numpy.ndarray

In [93]:
b

array([[18, 12, 12, 10],
       [16, 10, 12, 11],
       [19, 17, 15, 16],
       [12, 16, 15, 19],
       [15, 15, 17, 13]])

In [94]:
b[:]

array([[18, 12, 12, 10],
       [16, 10, 12, 11],
       [19, 17, 15, 16],
       [12, 16, 15, 19],
       [15, 15, 17, 13]])

In [95]:
b[1:3]

array([[16, 10, 12, 11],
       [19, 17, 15, 16]])

In [96]:
b

array([[18, 12, 12, 10],
       [16, 10, 12, 11],
       [19, 17, 15, 16],
       [12, 16, 15, 19],
       [15, 15, 17, 13]])

In [97]:
b[1,2]

12

In [98]:
b

array([[18, 12, 12, 10],
       [16, 10, 12, 11],
       [19, 17, 15, 16],
       [12, 16, 15, 19],
       [15, 15, 17, 13]])

In [100]:
b[1,3]

11

In [99]:
b[1,3]

11

In [101]:
b

array([[18, 12, 12, 10],
       [16, 10, 12, 11],
       [19, 17, 15, 16],
       [12, 16, 15, 19],
       [15, 15, 17, 13]])

In [102]:
b[2:3]

array([[19, 17, 15, 16]])

In [103]:
b

array([[18, 12, 12, 10],
       [16, 10, 12, 11],
       [19, 17, 15, 16],
       [12, 16, 15, 19],
       [15, 15, 17, 13]])

In [104]:
b[0:-2]

array([[18, 12, 12, 10],
       [16, 10, 12, 11],
       [19, 17, 15, 16]])

In [105]:
b

array([[18, 12, 12, 10],
       [16, 10, 12, 11],
       [19, 17, 15, 16],
       [12, 16, 15, 19],
       [15, 15, 17, 13]])

In [106]:
b[0,2]

12

In [107]:
b

array([[18, 12, 12, 10],
       [16, 10, 12, 11],
       [19, 17, 15, 16],
       [12, 16, 15, 19],
       [15, 15, 17, 13]])

In [108]:
b[-5,-3] 

12

In [109]:
b

array([[18, 12, 12, 10],
       [16, 10, 12, 11],
       [19, 17, 15, 16],
       [12, 16, 15, 19],
       [15, 15, 17, 13]])

In [110]:
b[-4,2] 

12

In [111]:
np.random.randint(10,20,(4,4))

array([[16, 14, 17, 17],
       [16, 19, 18, 15],
       [18, 17, 11, 11],
       [13, 19, 13, 19]])